### ISSUE TITLE
createFromConstantName: public or internal

### ISSUE THREAD

**Issue by MRdNk** [eskypl/enum#3]
https://github.com/eskypl/enum/blob/master/src/Esky/Enum/Enum.php#L44-L56

The doc block notes it as `* @internal param mixed $value` but the method is public and noted as an example in the readme.

**Comment by tkolodziej** [comment]
`@internal` tag does not tell about method visibility, it tell about internal / public, see: http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.internal.pkg.html . 
Nevertheless it isn't correct because it points to nonexistent param `$value` and will be fixed.
